
version: '3.11'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: propovedi88
      MYSQL_DATABASE: cd
      MYSQL_USER: root  
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/club-data.sql
